version: '3'

services:
  eurostreaming_telegrambot:
    image: matt0550/eurostreaming_telegrambot_telegrambot
    environment:
      - token=TG_TOKEN
      - owner_id=TG_OWNER_ID
      - enable_webapp_server=True # For the telegram webapp.
      - webserver_debug=False
      - report_errors_owner=True # Report errors to the owner.
      - secret_key=SECRET_KEY    # Random string
      - PUID=1000     # UID of the user inside the container, make sure it has access to the database file
      - PGID=1000     # GID of the user inside the container, make sure it has access to the database file
    ports:
      - 5040:5000
    restart: unless-stopped
